### PR TITLE
[RHPAM-2503]- Console UI - Support for mounting roleMapping and GitHooks

### PR DESCRIPTION
**Pull request by swati-kale**
Signed-off-by: Swati Kale <swkale@redhat.com>

### CODE REVIEW

**Comment by ruromero** [comment]
@swati-kale I think the console should leverage the operator for such complex validations and just render out back to the console the errors coming from the operator.
This is something that is not required right now so IMO just adding the new fields should be enough. They shouldn't be required.

**Comment by ruromero** [comment]
If this is too late for this release, ignore my comment. It can be reviewed in the next sprint

**Comment by yzhao583** [comment]
Generally looks good to me, if someone can provide more background info, I can provide more detail review thanks.

**Comment by swati-kale** [comment]
> If this is too late for this release, ignore my comment. It can be reviewed in the next sprint

@ruromero As discussed changed the descriptions and added  fieldgroup for RoleMapper.

**Comment by bmozaffa** [comment]
It sounds like this is ready to merge. Let's make sure to test properly before leveraging the commit in the BA operator code.

**Pull request merged**
