### PR TITLE
Updated labels, added descriptions, made some corrections

### PR DESCRIPTION
**Pull request by bmozaffa**
Updated labels and added descriptions, while also tweaking and correcting the form definition in certain spots

Signed-off-by: Babak Mozaffari <bmozaffa@redhat.com>

### CODE REVIEW

**Comment by sutaakar** [comment]
@bmozaffa What is the changed file used for? From the file path ( test/examples) I would guess that this file is used just for testing purposes. Is it so? What tests are using this?

**Comment by bmozaffa** [comment]
@sutaakar , the UI is typically defined declaratively by the calling operator, in our case, by the BA operator [form file](https://github.com/kiegroup/kie-cloud-operator/blob/master/deploy/ui/form.json). However, for local development and to run the UI outside of the operator, this form is duplicated in the UI project.

I was waiting to wrap up a few other changes, but it doesn't look like I'll be getting anywhere. So I will now update the operator with the latest console changes, including this file.

**Comment by sutaakar** [comment]
@bmozaffa Thanks. So any change related to Operator CRD should be also replicated to [this file](https://github.com/kiegroup/kie-cloud-operator/blob/master/deploy/ui/form.json), ideally also to file changed by this PR.

**Comment by bmozaffa** [comment]
@sutaakar Correct! Definitely to that file, and updating this one would be helpful at this point of development. If the change does not involve the UI, there would be no need to update this file/repo. The operator repo will just specify what the form should look like.

**Pull request merged**
