### PR TITLE
Form Data persistence

### PR DESCRIPTION
**Pull request by swati-kale**
Signed-off-by: Swati Kale <swkale@redhat.com>

### CODE REVIEW

**Comment by sutaakar** [comment]
@swati-kale hi, can you please describe what is implemented in this PR?

**Comment by swati-kale** [comment]
> @swati-kale hi, can you please describe what is implemented in this PR?

@sutaakar , The complete form is added and the data across the Wizard steps are persisted so that can be pulled int Yaml.

**Comment by swati-kale** [comment]
Except for nested components.

**Comment by sutaakar** [comment]
What do you mean by nested components, you mean deployed objects (Workbench, Kie server, Smart router)?

**Comment by swati-kale** [comment]
> What do you mean by nested components, you mean deployed objects (Workbench, Kie server, Smart router)?

Env and Server

**Comment by sutaakar** [comment]
Thanks, will try to build the UI and check

**Pull request merged**
