### PR TITLE
Removed "default" for extension images - Minor fix

### PR DESCRIPTION
**Pull request by swati-kale**
Signed-off-by: Swati Kale <swkale@redhat.com>

### CODE REVIEW

**Comment by bmozaffa** [comment]
Can you check and make sure the indent is correct on the curly braces?

**Comment by swati-kale** [comment]
I deleted the branch and hence the PR got closed automatically.

**Comment by swati-kale** [comment]
> Can you check and make sure the indent is correct on the curly braces?

Yes will do.

**Comment by swati-kale** [comment]
> > Can you check and make sure the indent is correct on the curly braces?
> 
> Yes will do.

Fixed the indentation

**Pull request merged**
