### PR TITLE
added min/max logic for adding dynamic elements to the page

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

### CODE REVIEW

**Comment by bmozaffa** [comment]
@ricardozanini First off, thank you for your help, it is much appreciated!

We have reorganized the folder structure a little bit as part of the build and deploy process, and index.html now goes under frontend/dist. Can you please do a rebase? You should also pick up the .gitignore which would prevent your bundle.js to be picked up as part of the commit.

**Comment by ricardozanini** [comment]
I'm not sure why this PR was closed, just squashed the commit /o\

**Comment by bmozaffa** [comment]
oh, weird, it shows you closed it!

**Comment by bmozaffa** [comment]
I think you ended up omitting your files and pushing the same thing that was in HEAD, so there was no difference and no PR.

**Comment by ricardozanini** [comment]
yeah, that's what's happened. Reviewed my history and found a `|` instead of `&&` in the git command. :/
I opened another one that will add this feature. At the end of the day I'll squash it. Thanks!!

**Pull request closed without merging**
